[package]
name = "swig-state"
version = "0.1.0"
edition = "2021"


[dependencies]
borsh = { version = "1.5.3", default-features = false, features = ["derive"] }
bytemuck = { version = "1.21.0", features = ["derive"] }
pinocchio = { version = "0.7.1" }
