[package]
name = "swig-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
swig-interface = { path = "../interface" }
swig-state-x = { path = "../state-x" }

solana-program = "2.0"
solana-sdk = "2.0"
solana-client = "2.0"
bs58 = "0.5.1"
hex = "0.4.3"
thiserror = "2.0.12"
anyhow = "1.0.75"
tokio = { version = "1.0", features = ["full"] }

[dev-dependencies]
test-log = "0.2"
rand = "0.8"
litesvm = { git = "https://github.com/litesvm/litesvm" }

[lints]
workspace = true
