use openssl::{
    bn::BigNumContext,
    ec::{EcGroup, EcPoint, PointConversionForm},
    nid::Nid,
};
use serde::Deserialize;
use solana_sdk::{pubkey, pubkey::Pubkey};
use swig_interface::reservation::{ReservationAddressOptions, ReservationError, ReservationV1};
use swig_state::{authority::AuthorityType, swig::swig_account_seeds};

const PROGRAM: Pubkey = pubkey!("swigypWHEksbC64pWKwah1WTeh9JXwx8H1rJHLdbQMB");
const ED_KEY: [u8; 32] = [
    0xd7, 0x5a, 0x98, 0x01, 0x82, 0xb1, 0x0a, 0xb7, 0xd5, 0x4b, 0xfe, 0xd3, 0xc9, 0x64, 0x07, 0x3a,
    0x0e, 0xe1, 0x72, 0xf3, 0xda, 0xa6, 0x23, 0x25, 0xaf, 0x02, 0x1a, 0x68, 0xf7, 0x07, 0x51, 0x1a,
];

// Copied from the authoritative design, rather than generated by this codec.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct ReferenceVector {
    authority_type: u16,
    public_key_hex: String,
    package_hex: String,
    commitment_hex: String,
    config: String,
    config_bump: u8,
    deposit: String,
    deposit_bump: u8,
}

#[test]
fn design_vectors_match_bytes_commitments_and_canonical_addresses(
) -> Result<(), Box<dyn std::error::Error>> {
    let vectors: Vec<ReferenceVector> =
        serde_json::from_str(include_str!("data/reservation-v1.json"))?;
    assert_eq!(vectors.len(), 3);
    for vector in vectors {
        let authority = AuthorityType::try_from(vector.authority_type)
            .map_err(|error| format!("invalid fixture authority: {error:?}"))?;
        let key = hex::decode(vector.public_key_hex)?;
        let package = ReservationV1::new(PROGRAM, authority, &key, Default::default())?;
        let addresses = package.addresses()?;
        assert_eq!(hex::encode(package.as_bytes()), vector.package_hex);
        assert_eq!(hex::encode(addresses.commitment), vector.commitment_hex);
        assert_eq!(addresses.swig_address.to_string(), vector.config);
        assert_eq!(addresses.swig_bump, vector.config_bump);
        assert_eq!(addresses.wallet_address.to_string(), vector.deposit);
        assert_eq!(addresses.wallet_bump, vector.deposit_bump);
        assert_eq!(
            ReservationV1::from_bytes(package.as_bytes(), PROGRAM)?,
            package
        );
        assert_eq!(
            package.as_bytes().len(),
            if vector.authority_type == 1 { 99 } else { 100 }
        );
        let legacy =
            Pubkey::find_program_address(&swig_account_seeds(&addresses.commitment), &PROGRAM);
        assert_ne!(addresses.swig_address, legacy.0);
    }
    Ok(())
}

#[test]
fn account_indices_and_custom_salts_have_the_exact_mapping(
) -> Result<(), Box<dyn std::error::Error>> {
    let default = ReservationV1::new(PROGRAM, AuthorityType::Ed25519, &ED_KEY, Default::default())?;
    for index in [0, 1, 255, 256, u32::MAX] {
        let package = ReservationV1::new(
            PROGRAM,
            AuthorityType::Ed25519,
            &ED_KEY,
            ReservationAddressOptions::AccountIndex(index),
        )?;
        let mut salt = [0; 32];
        salt[28..].copy_from_slice(&index.to_le_bytes());
        assert_eq!(&package.as_bytes()[33..65], &salt);
        assert_eq!(
            package,
            ReservationV1::new(
                PROGRAM,
                AuthorityType::Ed25519,
                &ED_KEY,
                ReservationAddressOptions::Salt(salt),
            )?
        );
        if index == 0 {
            assert_eq!(package, default);
        } else {
            assert_ne!(
                package.addresses()?.wallet_address,
                default.addresses()?.wallet_address
            );
        }
    }
    let mut salt = [0xa5; 32];
    salt[28..].copy_from_slice(&7u32.to_le_bytes());
    let package = ReservationV1::new(
        PROGRAM,
        AuthorityType::Ed25519,
        &ED_KEY,
        ReservationAddressOptions::Salt(salt),
    )?;
    assert_eq!(&package.as_bytes()[33..65], &salt);
    assert_eq!(
        ReservationV1::from_bytes(package.as_bytes(), PROGRAM)?,
        package
    );
    Ok(())
}

#[test]
fn sec1_encodings_normalize_to_the_same_package() -> Result<(), Box<dyn std::error::Error>> {
    let vectors: Vec<ReferenceVector> =
        serde_json::from_str(include_str!("data/reservation-v1.json"))?;
    for vector in vectors.into_iter().filter(|v| v.authority_type != 1) {
        let authority = AuthorityType::try_from(vector.authority_type)
            .map_err(|error| format!("invalid fixture authority: {error:?}"))?;
        let compressed = hex::decode(vector.public_key_hex)?;
        let group = EcGroup::from_curve_name(if authority == AuthorityType::Secp256k1 {
            Nid::SECP256K1
        } else {
            Nid::X9_62_PRIME256V1
        })?;
        let mut context = BigNumContext::new()?;
        let point = EcPoint::from_bytes(&group, &compressed, &mut context)?;
        let uncompressed =
            point.to_bytes(&group, PointConversionForm::UNCOMPRESSED, &mut context)?;
        let expected = ReservationV1::new(PROGRAM, authority, &compressed, Default::default())?;
        assert_eq!(
            ReservationV1::new(PROGRAM, authority, &uncompressed, Default::default())?,
            expected
        );
        if authority == AuthorityType::Secp256k1 {
            assert_eq!(
                ReservationV1::new(PROGRAM, authority, &uncompressed[1..], Default::default())?,
                expected
            );
        }
        // Imports must already be canonical, even when constructors accept SEC1.
        let expanded = [&expected.as_bytes()[..67], &uncompressed].concat();
        assert!(matches!(
            ReservationV1::from_bytes(&expanded, PROGRAM),
            Err(ReservationError::InvalidPackage)
        ));
    }
    Ok(())
}

#[test]
fn malformed_packages_are_rejected_at_the_encoding_boundary(
) -> Result<(), Box<dyn std::error::Error>> {
    let vectors: Vec<ReferenceVector> =
        serde_json::from_str(include_str!("data/reservation-v1.json"))?;
    for vector in vectors {
        let bytes = hex::decode(vector.package_hex)?;
        for length in 0..bytes.len() {
            assert!(
                matches!(
                    ReservationV1::from_bytes(&bytes[..length], PROGRAM),
                    Err(ReservationError::InvalidPackage)
                ),
                "accepted length {length}"
            );
        }
        for extra in [1, 2, 8, 100] {
            let padded = [bytes.clone(), vec![0; extra]].concat();
            assert!(matches!(
                ReservationV1::from_bytes(&padded, PROGRAM),
                Err(ReservationError::InvalidPackage)
            ));
        }
        for version in [0, 2, 255] {
            let mut bad = bytes.clone();
            bad[0] = version;
            assert!(matches!(
                ReservationV1::from_bytes(&bad, PROGRAM),
                Err(ReservationError::InvalidPackage)
            ));
        }
        for tag in [0u16, 2, 4, 6, 7, 8, 0x101, 0x300, u16::MAX] {
            let mut bad = bytes.clone();
            bad[65..67].copy_from_slice(&tag.to_le_bytes());
            assert!(matches!(
                ReservationV1::from_bytes(&bad, PROGRAM),
                Err(ReservationError::InvalidPackage)
            ));
        }
        assert!(matches!(
            ReservationV1::from_bytes(&bytes, Pubkey::new_from_array([9; 32])),
            Err(ReservationError::WrongProgram)
        ));
        // Parsing operates on bytes, without an alignment requirement.
        let unaligned = [&[0], bytes.as_slice()].concat();
        assert_eq!(
            ReservationV1::from_bytes(&unaligned[1..], PROGRAM)?.as_bytes(),
            bytes
        );
    }
    Ok(())
}

#[test]
fn unsupported_owners_and_invalid_keys_are_rejected() -> Result<(), Box<dyn std::error::Error>> {
    for authority in [
        AuthorityType::Ed25519Session,
        AuthorityType::Secp256k1Session,
        AuthorityType::Secp256r1Session,
        AuthorityType::ProgramExec,
        AuthorityType::ProgramExecSession,
    ] {
        assert!(matches!(
            ReservationV1::new(PROGRAM, authority, &ED_KEY, Default::default()),
            Err(ReservationError::UnsupportedAuthority)
        ));
    }
    for authority in [
        AuthorityType::Ed25519,
        AuthorityType::Secp256k1,
        AuthorityType::Secp256r1,
    ] {
        for key in [vec![], vec![0; 20], vec![0; 31], vec![0; 34], vec![0; 66]] {
            assert!(matches!(
                ReservationV1::new(PROGRAM, authority, &key, Default::default()),
                Err(ReservationError::InvalidPublicKey)
            ));
        }
    }
    // The derived PDA is off curve, so it cannot be a direct Ed25519 owner.
    let off_curve = Pubkey::find_program_address(&[b"owner"], &PROGRAM).0;
    assert!(matches!(
        ReservationV1::new(
            PROGRAM,
            AuthorityType::Ed25519,
            off_curve.as_ref(),
            Default::default()
        ),
        Err(ReservationError::InvalidPublicKey)
    ));
    let mut identity = [0; 32];
    identity[0] = 1;
    let mut noncanonical_identity = [255; 32];
    noncanonical_identity[0] = 0xee;
    noncanonical_identity[31] = 0x7f;
    for key in [[0; 32], identity, noncanonical_identity] {
        assert!(matches!(
            ReservationV1::new(PROGRAM, AuthorityType::Ed25519, &key, Default::default()),
            Err(ReservationError::InvalidPublicKey)
        ));
    }
    for authority in [AuthorityType::Secp256k1, AuthorityType::Secp256r1] {
        for prefix in [0, 1, 2, 3, 4, 6, 7, 255] {
            let mut key = [255; 33];
            key[0] = prefix;
            assert!(matches!(
                ReservationV1::new(PROGRAM, authority, &key, Default::default()),
                Err(ReservationError::InvalidPublicKey)
            ));
            let mut bytes = vec![1];
            bytes.extend_from_slice(PROGRAM.as_ref());
            bytes.extend_from_slice(&[0; 32]);
            bytes.extend_from_slice(&(authority as u16).to_le_bytes());
            bytes.extend_from_slice(&key);
            assert!(matches!(
                ReservationV1::from_bytes(&bytes, PROGRAM),
                Err(ReservationError::InvalidPublicKey)
            ));
        }
    }
    Ok(())
}

#[test]
fn commitment_binds_program_salt_owner_and_type() -> Result<(), Box<dyn std::error::Error>> {
    let base = ReservationV1::new(PROGRAM, AuthorityType::Ed25519, &ED_KEY, Default::default())?;
    let other_program = ReservationV1::new(
        Pubkey::new_from_array([9; 32]),
        AuthorityType::Ed25519,
        &ED_KEY,
        Default::default(),
    )?;
    let other_salt = ReservationV1::new(
        PROGRAM,
        AuthorityType::Ed25519,
        &ED_KEY,
        ReservationAddressOptions::AccountIndex(1),
    )?;
    let mut negated_owner = ED_KEY;
    negated_owner[31] ^= 0x80;
    let other_owner = ReservationV1::new(
        PROGRAM,
        AuthorityType::Ed25519,
        &negated_owner,
        Default::default(),
    )?;
    for changed in [other_program, other_salt, other_owner] {
        assert_ne!(
            base.addresses()?.commitment,
            changed.addresses()?.commitment
        );
        assert_ne!(
            base.addresses()?.wallet_address,
            changed.addresses()?.wallet_address
        );
    }
    // x=6 with even y is valid on both curves: changing only the authority tag
    // must still commit to a different owner type and address.
    let mut key = [0; 33];
    key[0] = 2;
    key[32] = 6;
    let k1 = ReservationV1::new(PROGRAM, AuthorityType::Secp256k1, &key, Default::default())?;
    let r1 = ReservationV1::new(PROGRAM, AuthorityType::Secp256r1, &key, Default::default())?;
    assert_ne!(k1.addresses()?.commitment, r1.addresses()?.commitment);
    assert_ne!(
        k1.addresses()?.wallet_address,
        r1.addresses()?.wallet_address
    );
    Ok(())
}
