[package]
name = "no-padding"
version.workspace = true
edition = "2021"
license = "AGPL-3.0"
authors.workspace = true
documentation.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"

[lints]
workspace = true
