[package]
name = "swig-state-x"
version = "0.1.0"
edition = "2021"

[dependencies]
pinocchio = { version = "0.8.1", features = ["std"] }
static_assertions = "1.1.0"
swig-assertions = { path = "../assertions" }
