name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  RUST_VERSION: 1.82.0
  SOLANA_VERSION: 2.0.13
  CARGO_TERM_COLOR: always
  RUSTC_WRAPPER: sccache
  SCCACHE_GHA_ENABLED: true
  SCCACHE_CACHE_SIZE: 2G

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: rustfmt, clippy, rust-analyzer

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.8

      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Solana
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v${{ env.SOLANA_VERSION }}/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          solana --version

      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest

      - name: Build Solana Program
        run: |
          cargo build-sbf --manifest-path program/Cargo.toml

      - name: Run Rust Tests with nextest
        run: |
          cargo nextest run --all --workspace --no-fail-fast --junit output.xml

      - name: Run Solana Program Tests
        run: |
          cargo test-sbf --manifest-path program/Cargo.toml

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: output.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: "output.xml"
          check_name: "Test Results"
