name: Lint and Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  RUST_VERSION: 1.82.0
  CARGO_TERM_COLOR: always
  RUSTC_WRAPPER: sccache
  SCCACHE_GHA_ENABLED: true
  SCCACHE_CACHE_SIZE: 2G

jobs:
  lint:
    runs-on: ubuntu-latest-m
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: rustfmt, clippy, rust-analyzer

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.4

      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-lint-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-lint-

      - name: Check formatting
        run: |
          cargo fmt --all -- --check

      # - name: Run clippy
      #   run: |
      #     cargo clippy --all-features -- -D warnings
